# Originally generated by `nixos-generate-config`, now maintained by hand.
# Hardware-detected facts only (disks, kernel modules, microcode); anything
# you'd choose rather than detect belongs in ../hosts/suspense.nix.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # "nvme" is not optional here: /nix lives on nvme0n1p1 (see below) and
  # stage 1 has to mount it before switch-root. Without the driver in the
  # initrd the boot drops to an emergency shell.
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Do not bother setting boot.initrd.systemd.enable here: it is already the
  # default on this nixpkgs, and stage 1 is demonstrably systemd -- the boot
  # journal carries Initrd Root Device / Initrd Default Target /
  # initrd-switch-root.service, none of which exist under the old shell
  # script. Setting it explicitly produces a byte-identical initrd. Checked
  # while chasing boot time; recorded so nobody re-tests it as a speedup.

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/512871c4-6331-46d1-84b0-060c12d33472";
      fsType = "ext4";
    };

  # The 1000M ESP on the second SATA disk, not the 512M one this install
  # started on. 512M cannot hold even two generations once the nvidia modules
  # are in the initrd (~190 MiB each), which is the whole reason for the move.
  #
  # The old 512M ESP (UUID B623-38FF, PARTUUID bf10756a-...) is still on disk,
  # still has its NVRAM entry, and still has the generations that were current
  # when this switched. Left deliberately as the recovery path -- F11 at POST
  # picks it. Reformat it only once this one has proven itself.
  #
  # Note the device names on this box are not stable: the live /boot has been
  # both sda1 and sdb1 across consecutive boots. Always identify these two
  # partitions by UUID or PARTUUID, never by /dev/sdX.
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA92-7527";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # The Nix store on its own filesystem, on the 238G NVMe in the board's M.2
  # slot. The store is ~2.9M small files and nix's own workloads (eval,
  # builds, GC) are almost pure small random reads -- the one thing SATA is
  # worst at and this drive is best at. Everything else stayed on the SATA
  # SSDs: /home is 240G and would not fit, and the rest of / is ~5G of cold
  # config and append-only logs, so moving it would buy nothing.
  #
  # The drive is a DRAM-less MAXIO controller (PCI 0x1e4b) but Host Memory
  # Buffer is active, so the FTL map lives in RAM and random reads do not pay
  # the usual DRAM-less penalty.
  #
  # neededForBoot is already implied -- lib/utils.nix treats /nix as
  # needed-for-boot unconditionally -- but stating it means the next reader
  # does not have to know that.
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/50e381b3-99f0-457e-866a-d74be13b7685";
      fsType = "ext4";
      options = [ "noatime" ];
      neededForBoot = true;
    };

  # nofail is about boot ordering, not about tolerating a missing disk. Without
  # it this mount is Before=local-fs.target, so it became the head of the
  # critical chain once nvidia stopped being: fsck at 1.610s -> mount at 1.908s
  # -> local-fs.target -> sysinit -> NetworkManager -> graphical.target. A
  # bulk data disk has no business gating the login screen. nofail drops both
  # the requirement and that ordering, so it mounts alongside the rest of boot
  # instead of in front of it.
  fileSystems."/home/dlangevi/storage" =
    { device = "/dev/disk/by-uuid/8ac0fb0f-0c0b-4f90-9227-f04267dd22ba";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.device-timeout=10s" ];
    };

  # sda3 -- a 17G swap partition that has existed (formatted, labelled "swap")
  # since the pre-NixOS EndeavourOS install, but was never declared here, so
  # nothing ever ran swapon against it.
  #
  # With 32G of RAM this is not about routine paging; it is headroom for the
  # tail. Nix builds fan out to $NIX_BUILD_CORES parallel compiler processes and
  # a single unlucky C++ or Rust link can transiently want several GB, which is
  # exactly the case where the OOM killer takes out the build instead.
  swapDevices = [
    { device = "/dev/disk/by-uuid/42c8315e-8878-4c24-bea3-34145772fdfe"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
