# Originally generated by `nixos-generate-config`, now maintained by hand.
# Hardware-detected facts only (disks, kernel modules, microcode); anything
# you'd choose rather than detect belongs in ../hosts/suspense.nix.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/512871c4-6331-46d1-84b0-060c12d33472";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B623-38FF";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/dlangevi/storage" =
    { device = "/dev/disk/by-uuid/8ac0fb0f-0c0b-4f90-9227-f04267dd22ba";
      fsType = "ext4";
    };

  # sda3 -- a 17G swap partition that has existed (formatted, labelled "swap")
  # since the pre-NixOS EndeavourOS install, but was never declared here, so
  # nothing ever ran swapon against it.
  #
  # With 32G of RAM this is not about routine paging; it is headroom for the
  # tail. Nix builds fan out to $NIX_BUILD_CORES parallel compiler processes and
  # a single unlucky C++ or Rust link can transiently want several GB, which is
  # exactly the case where the OOM killer takes out the build instead.
  swapDevices = [
    { device = "/dev/disk/by-uuid/42c8315e-8878-4c24-bea3-34145772fdfe"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
