{ pkgs, ... }:

let
  mountPoint = "/mnt/dance/storage";
in
{
  # dance holds the 916G storage NVMe (music library, OBS recordings, video)
  # and is always up, so suspense mounts it over sshfs rather than keeping a
  # second copy. Read-write: the point is to move files onto dance from here.
  #
  # The hard requirement is that dance being down must never cost anything.
  # `noauto` + `x-systemd.automount` means nothing is mounted until something
  # touches the mountpoint, so boot and nixos-rebuild never wait on dance; the
  # timeouts below then turn an access-while-down into a prompt error rather
  # than an indefinite hang.
  #
  # sshfs is deliberately not in fileSystems on any other host -- this is
  # suspense reaching out to dance, not a shared fact about the fleet.
  fileSystems.${mountPoint} = {
    device = "dance@dance:/home/dance/storage";
    fsType = "sshfs";
    options = [
      # Mount on first access only. Without these three a dance that is down
      # blocks boot until the mount times out.
      "noauto"
      "x-systemd.automount"
      "_netdev"

      # Fail fast when dance is unreachable. ConnectTimeout bounds the TCP
      # connect; mount-timeout bounds the whole mount attempt, so the worst
      # case a caller sees is ~10s rather than a hang.
      "ConnectTimeout=5"
      "x-systemd.mount-timeout=10s"

      # Drop the mount once it has been idle for 10 minutes, so a dance that
      # disappears can't leave a wedged FUSE handle behind indefinitely.
      "x-systemd.idle-timeout=600"

      # Survive dance rebooting or the link dropping mid-mount. Note this
      # recovers the *mount*; a write interrupted partway is still a partial
      # file on dance.
      "reconnect"
      "ServerAliveInterval=15"
      "ServerAliveCountMax=3"

      # A system mount runs as root, so it needs root's key rather than
      # dlangevi's. Generated by hand (there is no secrets tooling in this
      # repo); only the public half is committed, into dance's
      # authorizedKeys in nixos/hosts/dance.nix.
      "IdentityFile=/root/.ssh/id_ed25519_dance"

      # dance:dance is uid 1000 gid 100 and dlangevi:users is uid 1000 gid
      # 100, so ownership maps straight through with no idmap needed.
      # allow_other is what lets dlangevi see a root-made mount at all.
      "allow_other"
    ];

    # Without this NixOS emits fsck pass 2 in fstab, which makes no sense for
    # a network filesystem and pulls in a systemd-fsck dependency.
    noCheck = true;
  };

  # Provides mount.fuse.sshfs, which the fsType above resolves to.
  system.fsPackages = [ pkgs.sshfs ];

  # Required for the allow_other option.
  programs.fuse.userAllowOther = true;

  # Pin dance's host key rather than leaving root to trust-on-first-use. A
  # system mount has no one at a terminal to answer the prompt.
  programs.ssh.knownHosts.dance = {
    hostNames = [ "dance" "100.66.232.127" ];
    publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO3gtW3x7CwhyE+GSrfLMhO9tEJrqFYBsO6R+EtovfSF";
  };
}
