# The freelancing pitch page at hire.dlangevi.com.
#
# Deliberately separate from media-audio.nix: it shares that module's nginx
# and its Cloudflare ACME credentials, but it has nothing to do with the
# household media services and shouldn't be rebuilt or reasoned about
# alongside them.
{ ... }:

let
  siteDir = "/srv/www/freelance";

  # A sibling of dlangevi.com rather than a name under jpc.dlangevi.com,
  # even though the existing `*.jpc.dlangevi.com` wildcard would have covered
  # the latter for free. This page is meant to go public under its own name
  # eventually, and renaming a URL people have been given is worse than the
  # one extra cert.
  #
  # Today it resolves only through the UDM Pro's local DNS override pointing
  # at this box's LAN IP -- there is no public A record, so the site is
  # LAN/tailnet only. Publishing it later is a DNS change, not a rebuild.
  siteDomain = "hire.dlangevi.com";

  # Same Cloudflare token as the jpc cert: dlangevi.com is a single zone on
  # Cloudflare, so one Zone:DNS:Edit token covers both names. DNS-01 again,
  # because HTTP-01 would require this box to be reachable from the internet
  # -- which is exactly what it isn't.
  cloudflareCredentialsFile = "/var/lib/secrets/cloudflare-jpc-acme.env";
in
{
  # Content is rsynced in and edited in place, not generated by Nix -- same
  # reasoning as the jpc landing page. Copy changes on a marketing page
  # shouldn't cost a system rebuild.
  systemd.tmpfiles.rules = [
    "d /srv/www 0755 root root -"
    "d ${siteDir} 0755 dance users -"
  ];

  security.acme.certs.${siteDomain} = {
    dnsProvider = "cloudflare";
    environmentFile = cloudflareCredentialsFile;
    group = "nginx";
  };

  services.nginx.virtualHosts.${siteDomain} = {
    useACMEHost = siteDomain;
    onlySSL = true;
    locations."/" = {
      root = siteDir;
      index = "index.html";
    };
  };
}
