# Music streaming (Navidrome) plus the dance:80 landing page that links to it.
#
# Split out of media-video.nix because audio moved off the workstation. dance is
# a Beelink SER8 that idles at 8-9 W and is already on 24/7, against suspense's
# 60-80 W -- roughly $72/yr at Seattle City Light's 13.38c/kWh. Audio never
# transcodes on the LAN, so this host needs no GPU, no VAAPI and no transcoding
# headroom; Navidrome itself runs in ~50 MB and speaks Subsonic natively.
#
# LAN plus tailnet only.
{ config, pkgs, lib, ... }:

let
  # The library lives on the storage NVMe and is exposed read-only at
  # /srv/media/music, which is what navidrome reads.
  #
  # The indirection is necessary: /home/dance is 0700, so navidrome's
  # DynamicUser cannot traverse into it. A bind mount sidesteps that because
  # permission checks apply to the components of the NEW path, not the
  # original's parents -- the same trick media-video.nix uses on suspense.
  # chmod o+x on the home directory would be the alternative and would weaken
  # it for every service on the box.
  #
  # It sits on the storage drive rather than root because the library is ~157 GB
  # post-transcode and heading for ~780 GB, while root also carries the OS and
  # 119 GB of itgmania.
  storeDir = "/home/dance/storage/music";
  musicDir = "/srv/media/music";

  # The JPC landing page (nginx's "/" on dance:80) is its own plain git repo,
  # edited in place -- not generated by Nix -- so residents-facing content
  # can change without a rebuild. Nix's only job is to make the directory
  # exist with the right ownership.
  landingDir = "/srv/www/jpc-landing";

  lanSubnet = "10.0.70.0/24";
  # Tailscale hands out addresses from the CGNAT range. Scoping to this rather
  # than trusting tailscale0 wholesale keeps the same posture as the LAN rule:
  # only the service ports are reachable, not every service on the box.
  tailnet = "100.64.0.0/10";
  navidromePort = 4533;
in
{
  # 0755 because the navidrome unit uses DynamicUser, so there is no stable uid
  # to grant access to; dance owns the directory so rsync can write into it.
  systemd.tmpfiles.rules = [
    "d /srv/media 0755 root root -"
    "d ${storeDir} 0755 dance users -"
    "d /srv/www 0755 root root -"
    "d ${landingDir} 0755 dance users -"
  ];

  # Read-only: navidrome never writes to the library, and transfers target
  # storeDir directly as user dance. `depends` is load-bearing -- without it
  # the bind can run before the storage disk is mounted and would silently
  # bind an empty directory, leaving navidrome with no library.
  fileSystems.${musicDir} = {
    device = storeDir;
    fsType = "none";
    options = [ "bind" "ro" ];
    depends = [ "/home/dance/storage" ];
  };

  services.navidrome = {
    enable = true;
    # Deliberately false: openFirewall opens on every interface. The scoped
    # rules below are the point.
    openFirewall = false;
    settings = {
      MusicFolder = musicDir;
      Address = "0.0.0.0";
      Port = navidromePort;
      # The library is large and mostly static. Full rescans only when tags
      # change, not on every startup.
      ScanSchedule = "@every 24h";
    };
  };

  # Remote access. No port forwarding, no dynamic DNS, works through CGNAT.
  services.tailscale = {
    enable = true;
    # Without this the daemon cannot accept inbound UDP on 41641, so peers fall
    # back to DERP relays -- which works, but adds latency.
    openFirewall = true;
  };

  # `http://dance` is a landing page for JPC residents, linking out to the
  # tools running on this box (Navidrome now, Jellyfin once it migrates
  # here) rather than dropping straight into one of them. Navidrome itself
  # stays reachable directly on navidromePort -- the landing page just
  # links to it -- so its SPA keeps assuming it's served from the root.
  services.nginx = {
    enable = true;
    virtualHosts."dance" = {
      # Bare hostnames arrive with whatever Host header the client felt like
      # sending (`dance`, the tailnet FQDN, a raw IP), so this vhost has to
      # answer for all of them.
      default = true;
      locations."/" = {
        root = landingDir;
        index = "index.html";
      };
    };
  };

  networking.firewall.extraCommands =
    let allow = subnet: port:
      "iptables -A nixos-fw -p tcp -s ${subnet} --dport ${toString port} -j nixos-fw-accept";
    in ''
      ${allow lanSubnet navidromePort}
      ${allow tailnet navidromePort}
      ${allow lanSubnet 80}
      ${allow tailnet 80}
    '';
}
