# dance's full media stack: Navidrome (music), Jellyfin (movies/shows), and
# the dance:80 landing page that links to both.
#
# dance is a Beelink SER8 that idles at 8-9 W and is already on 24/7, against
# suspense's 60-80 W -- roughly $72/yr at Seattle City Light's 13.38c/kWh.
# Movies/shows moved here from suspense along with Jellyfin itself; the
# Radeon 780M iGPU handles transcoding via VAAPI instead of suspense's GTX
# 1060 NVENC.
#
# LAN plus tailnet only.
{ config, pkgs, lib, ... }:

let
  # The library lives on the storage NVMe and is exposed read-only at
  # /srv/media/music, which is what navidrome reads.
  #
  # The indirection is necessary: /home/dance is 0700, and navidrome runs as
  # its own user (uid 991, group navidrome), which is in none of dance's
  # groups, so it cannot traverse into it. A bind mount sidesteps that because
  # permission checks apply to the components of the NEW path, not the
  # original's parents -- the same trick media-video.nix uses on suspense.
  # chmod o+x on the home directory would be the alternative and would weaken
  # it for every service on the box.
  #
  # It sits on the storage drive rather than root because the library is ~157 GB
  # post-transcode and heading for ~780 GB, while root also carries the OS and
  # 119 GB of itgmania.
  storeDir = "/home/dance/storage/music";
  musicDir = "/srv/media/music";

  # Movies and shows live on their own 2TB USB drive, mounted alongside the
  # storage NVMe at /home/dance/storage/video (that drive also catches OBS
  # stream recordings, hence living under storage/ rather than somewhere
  # movie/show-specific). Same bind-mount trick as storeDir/musicDir gets
  # them into Jellyfin's view.
  videoStorage = "/home/dance/storage/video";
  moviesStoreDir = "${videoStorage}/movies";
  showsStoreDir = "${videoStorage}/shows";
  moviesDir = "/srv/media/movies";
  showsDir = "/srv/media/shows";
  jellyfinPort = 8096;

  # Neighbour-contributed media, kept as separate Jellyfin/Navidrome
  # libraries within these same two instances (both support multiple
  # libraries with per-user access permissions) rather than as separate
  # services -- so residents and neighbours share dTunes/dFlix, just with
  # different accounts scoped to different libraries. Nix's only job here is
  # to make the directories exist; adding the libraries and the
  # neighbours-facing accounts happens in each app's own admin UI.
  jpcMusicDir = "/srv/media/jpc-music";
  jpcMoviesDir = "/srv/media/jpc-movies";
  jpcShowsDir = "/srv/media/jpc-shows";

  # The JPC landing page (nginx's "/" on dance:80) is its own plain git repo,
  # edited in place -- not generated by Nix -- so residents-facing content
  # can change without a rebuild. Nix's only job is to make the directory
  # exist with the right ownership.
  landingDir = "/srv/www/jpc-landing";

  lanSubnet = "10.0.70.0/24";
  # Tailscale hands out addresses from the CGNAT range. Scoping to this rather
  # than trusting tailscale0 wholesale keeps the same posture as the LAN rule:
  # only the service ports are reachable, not every service on the box.
  tailnet = "100.64.0.0/10";
  navidromePort = 4533;

  # Public domain (dlangevi.com, registered through Squarespace) for a
  # warning-free https:// on the landing page. jpc.dlangevi.com only ever
  # resolves to this box's LAN IP (via a local DNS override on the UDM Pro,
  # not a public record) -- it's still LAN/tailnet only, same as `dance`.
  # It gets a real Let's Encrypt cert anyway, because cert issuance only
  # proves DNS-zone control, not that the box is internet-reachable.
  #
  # Squarespace has no DNS API, so DNS-01 can't run against it directly
  # (neither acme.sh nor certbot has a Squarespace plugin, and Squarespace's
  # own forums confirm there isn't one). Workaround: dlangevi.com's DNS was
  # moved to Cloudflare (nameservers repointed at the registrar), so ACME
  # talks to Cloudflare's API instead. Cloudflare's per-subdomain "subdomain
  # setup" (delegating only `jpc` while leaving the rest of the domain on
  # Squarespace) is Enterprise-only, which is why this is a whole-domain
  # migration rather than a narrower NS delegation.
  jpcDomain = "jpc.dlangevi.com";
  cloudflareCredentialsFile = "/var/lib/secrets/cloudflare-jpc-acme.env";

  # Navidrome and Jellyfin are reverse-proxied under their own subdomains
  # (rather than a path prefix on jpcDomain) because both are SPAs that
  # assume they're served from the root of whatever origin they're on --
  # same reason the landing page links to their bare ports today instead of
  # a subpath. A wildcard on the existing DNS-01 cert covers both for free.
  tunesSubdomain = "tunes.${jpcDomain}";
  flixSubdomain = "flix.${jpcDomain}";
in
{
  # 0755 because navidrome's user shares no group with dance, so world-read is
  # the only thing that reaches it; dance owns the directory so rsync can
  # write into it. Files need the same treatment -- see the --chmod in cdrip's
  # transfer, since beets writes converted tracks as 0600.
  systemd.tmpfiles.rules = [
    "d /srv/media 0755 root root -"
    "d ${storeDir} 0755 dance users -"
    "d ${moviesStoreDir} 0755 dance users -"
    "d ${showsStoreDir} 0755 dance users -"
    "d ${jpcMusicDir} 0755 dance users -"
    "d ${jpcMoviesDir} 0755 dance users -"
    "d ${jpcShowsDir} 0755 dance users -"
    "d /srv/www 0755 root root -"
    "d ${landingDir} 0755 dance users -"
  ];

  # Read-only: navidrome never writes to the library, and transfers target
  # storeDir directly as user dance. `depends` is load-bearing -- without it
  # the bind can run before the storage disk is mounted and would silently
  # bind an empty directory, leaving navidrome with no library.
  fileSystems.${musicDir} = {
    device = storeDir;
    fsType = "none";
    options = [ "bind" "ro" ];
    depends = [ "/home/dance/storage" ];
  };

  # Same reasoning as the music bind above, `depends` on videoStorage rather
  # than /home/dance/storage since these live on the separate USB drive.
  fileSystems.${moviesDir} = {
    device = moviesStoreDir;
    fsType = "none";
    options = [ "bind" "ro" ];
    depends = [ videoStorage ];
  };

  fileSystems.${showsDir} = {
    device = showsStoreDir;
    fsType = "none";
    options = [ "bind" "ro" ];
    depends = [ videoStorage ];
  };

  # A "Neighbours" entry in Navidrome's sidebar: pick a neighbour, get their
  # albums. Navidrome has no extension point for this -- its plugin
  # capabilities (lifecycle, lyrics, metadata_agent, scheduler_callback,
  # scrobbler, sonic_similarity, taskworker, websocket_callback) do not touch
  # the web UI -- so the frontend is patched. nixpkgs builds the UI from
  # source, which is what makes that possible.
  #
  # The patch is frontend-only, and small, because everything under it
  # already exists: album_repository registers a filter for every
  # album-level tag on its own, /api/tag already serves tag values with
  # album counts, and AlbumFilter already narrows that by `tag_name` for its
  # own recordlabel and grouping inputs. All that is added is a React
  # resource listing the `neighbour` tag's values, each linking to the album
  # list filtered by it.
  #
  # The cost is that dance rebuilds navidrome from source, and the patch may
  # need rebasing when upstream touches App.jsx or en.json.
  nixpkgs.overlays = [
    (final: prev: {
      navidrome = prev.navidrome.overrideAttrs (old: {
        patches = (old.patches or [ ]) ++ [ ../patches/navidrome-neighbours.patch ];
      });
    })
  ];

  services.navidrome = {
    enable = true;
    # Deliberately false: openFirewall opens on every interface. The scoped
    # rules below are the point.
    openFirewall = false;
    settings = {
      MusicFolder = musicDir;
      Address = "0.0.0.0";
      Port = navidromePort;
      # The library is large and mostly static. Full rescans only when tags
      # change, not on every startup.
      ScanSchedule = "@every 24h";

      # NEIGHBOUR records who lent a disc in the JPC library; cdrip writes it
      # into every track it rips. Declaring it here is what makes Navidrome
      # keep the value instead of discarding it as an unknown comment.
      #
      # Album = true keeps the tag on the album row. Without it,
      # Album.SetTags deletes any tag not marked album-level, so albums carry
      # no neighbour at all and cannot be filtered by one.
      #
      # An earlier comment here claimed this would fold the tag into album
      # PID generation and re-key existing albums. That was wrong, taken from
      # the docs' wording rather than the code: computePID walks the explicit
      # PID.Album spec
      # ("musicbrainz_albumid|albumartistid,album,albumversion,releasedate")
      # and never iterates album-level tags, so a tag not named there has no
      # bearing on album identity.
      #
      # Changing tag configuration needs a full rescan to take effect.
      Tags.neighbour.Aliases = [ "neighbour" ];
      Tags.neighbour.MaxLength = 64;
      Tags.neighbour.Album = true;
    };
  };

  # The navidrome unit runs chrooted (RootDirectory=/run/navidrome) and only
  # auto-binds settings.MusicFolder into that jail. Navidrome itself supports
  # adding further libraries through its own UI, but any path not listed here
  # is invisible to the process -- attempting to add one from the UI fails
  # with "Invalid Library Path" even though the directory exists on disk.
  # Add each additional library's path here as it's introduced.
  systemd.services.navidrome.serviceConfig.BindReadOnlyPaths = [
    jpcMusicDir
  ];

  # VAAPI hardware transcoding on the Radeon 780M iGPU.
  hardware.graphics.enable = true;

  services.jellyfin = {
    enable = true;
    # Deliberately false: openFirewall opens on every interface. The scoped
    # rules below are the point.
    openFirewall = false;
    hardwareAcceleration = {
      enable = true;
      type = "vaapi";
      device = "/dev/dri/renderD128";
    };
    transcoding.enableHardwareEncoding = true;
  };

  # renderD128 is currently world-accessible on this box, but group
  # membership is the correct posture if udev rules ever tighten it back to
  # the usual 0660 root:render.
  users.users.jellyfin.extraGroups = [ "render" ];

  # Remote access. No port forwarding, no dynamic DNS, works through CGNAT.
  services.tailscale = {
    enable = true;
    # Without this the daemon cannot accept inbound UDP on 41641, so peers fall
    # back to DERP relays -- which works, but adds latency.
    openFirewall = true;
  };

  # DNS-01 against Cloudflare, for the jpc.dlangevi.com vhost below. The
  # credentials file just needs one line -- CF_DNS_API_TOKEN=... -- for a
  # token scoped to Zone:DNS:Edit on the delegated zone, created out of
  # band (root:root 600; systemd reads it as root before the acme service
  # drops privileges, so it never needs to be readable by the unprivileged
  # `acme` user).
  security.acme = {
    acceptTerms = true;
    defaults.email = "dav.langevin@gmail.com";
    certs.${jpcDomain} = {
      dnsProvider = "cloudflare";
      environmentFile = cloudflareCredentialsFile;
      # Covers tunesSubdomain and flixSubdomain too. Only possible because
      # this is DNS-01 -- HTTP-01 can't validate a wildcard at all.
      extraDomainNames = [ "*.${jpcDomain}" ];
      # So nginx (which runs as its own user) can read the issued cert/key.
      group = "nginx";
    };
  };

  # `http://dance` is a landing page for JPC residents, linking out to the
  # tools running on this box (Navidrome, Jellyfin) rather than dropping
  # straight into one of them. Each service stays reachable directly on its
  # own port -- the landing page just links out -- so their SPAs keep
  # assuming they're served from the root.
  services.nginx = {
    enable = true;
    # Forwards Host/X-Real-IP/X-Forwarded-* correctly to Navidrome and
    # Jellyfin below -- both care about the real client IP (e.g. Jellyfin's
    # login attempt limiting) and about Host for building absolute URLs.
    recommendedProxySettings = true;

    virtualHosts."dance" = {
      # Bare hostnames arrive with whatever Host header the client felt like
      # sending (`dance`, the tailnet FQDN, a raw IP), so this vhost has to
      # answer for all of them.
      default = true;
      locations."/" = {
        root = landingDir;
        index = "index.html";
      };
    };

    # https:// only works for requests to jpcDomain specifically -- that's
    # the one name the Cloudflare-issued cert above covers. Plain `dance`
    # still only gets http://.
    virtualHosts.${jpcDomain} = {
      useACMEHost = jpcDomain;
      onlySSL = true;
      locations."/" = {
        root = landingDir;
        index = "index.html";
      };
    };

    virtualHosts.${tunesSubdomain} = {
      useACMEHost = jpcDomain;
      onlySSL = true;
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString navidromePort}";
        proxyWebsockets = true;
      };
    };

    virtualHosts.${flixSubdomain} = {
      useACMEHost = jpcDomain;
      onlySSL = true;
      locations."/" = {
        proxyPass = "http://127.0.0.1:${toString jellyfinPort}";
        proxyWebsockets = true;
      };
    };
  };

  networking.firewall.extraCommands =
    let allow = subnet: port:
      "iptables -A nixos-fw -p tcp -s ${subnet} --dport ${toString port} -j nixos-fw-accept";
    in ''
      ${allow lanSubnet navidromePort}
      ${allow tailnet navidromePort}
      ${allow lanSubnet jellyfinPort}
      ${allow tailnet jellyfinPort}
      ${allow lanSubnet 80}
      ${allow tailnet 80}
      ${allow lanSubnet 443}
      ${allow tailnet 443}
    '';
}
